### ISSUE TITLE
Incorrect URLs in metadata yaml

### ISSUE THREAD

**Issue by pbuttigieg** [EcologicalSemantics/ecocore#11]
https://github.com/EcologicalSemantics/ecocore/blob/83e1ef267d39d70c185ee42133d9e23ddbe40d73/src/metadata/ecocore.yml#L7-L8

Seems that the OSK points to the github page literally. Apparently linked to the MD file. @ramonawalls has more detail and will post here ...

**Comment by ramonawalls** [comment]
If you look at ecocore/src/metadata/ecocore.md, you will see that it appears that the value for title is being used for the urls, instead of the value of id:

---
layout: ontology_detail
id: ecocore
title: An ontology of core ecological entities
jobs:
  - id: https://travis-ci.org/EcologicalSemantics/an-ontology-of-core-ecological-entities
    type: travis-ci
...

I'm going to fix this manually before making the PURL request, so you will need to look at an older commit to see the error.
