### ISSUE TITLE
suspension feeder vs filter feeder

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#87]
@jhammock
What's the difference? The EOL definitions seem pretty similar.

**Comment by diatomsRcool** [comment]
And what is the difference with planktivore?

**Comment by jhammock** [comment]
I think it might go like this:

planktivore
  suspension feeder
    filter feeder

If you eat plankton, it might be trying to evade you and you could be an ambush predator. 

Suspension feeders eat particles suspended in the water column (passively floating rather than swimming, is my understanding) but they might use any method, eg: [a feeding current](http://www.oceanlifecentre.dk/News/2014/12/Rodrigo) with individual particle capture. 

A filter feeder does this with a filter.

You could upend that hierarchy by arguing some filter feeder prey were swimming when they were caught by the filter. That would make filter feeder a direct child of planktivore, I expect.

**Comment by diatomsRcool** [comment]
So my understanding of planktonic is not that that animal doesn't swim, its that even if it does swim, its not strong enough to counter water movement. Does that make sense?

**Comment by jhammock** [comment]
That could make synonyms of planktotroph and suspension feeder... Oh. If plankton includes dead particles, which suspension feeders could be eating. If it doesn't, suspension feeder could be the parent of planktotroph and filter feeder...

**Comment by jhammock** [comment]
OK, and suspension feeder is a child of heterotroph, I expect? That would work for me

**Comment by jhammock** [comment]
Aeroplanktonivory is not much known (per google) but aeroplankton is. I don't much care either way. We have no data in that part of the definition yet, and we would make a separate term for it if we found some, I'm sure. The question is, should an aeroplanktivore be sibling or child to the planktivore we start with?

**Comment by diatomsRcool** [comment]
Yes. heterotroph.

I ask about the air/water thing because suspension feeder has "water" baked in while the EOL definition of plankton has air and water baked in. It may not be an issue.

**Comment by jhammock** [comment]
I'd be ok with baking the water into planktotroph for consistency. I like aeroplankton and aeroplanktivory as siblings of their aquatic counterparts if they ever crop up.

**Comment by diatomsRcool** [comment]
In v2019-03-15
